-- Seed the initial B.I.T.S Pakistan HDD catalogue.
-- Stable IDs and slugs make this migration safe to apply once in every environment.
INSERT INTO "Product" (
    "id",
    "slug",
    "name",
    "description",
    "price",
    "images",
    "category",
    "brand",
    "storageSize",
    "warrantyMonths",
    "inStock",
    "storeId",
    "createdAt",
    "updatedAt"
)
VALUES
    (
        'seed-hdd-500gb',
        'hdd-500gb',
        'HDD 500GB',
        '500 GB hard disk drive for desktop computers, CCTV recorders, DVRs, NVRs, and general storage use.',
        4000,
        ARRAY['/uploads/bits-logo.png'],
        'HDD',
        'Mixed',
        '500 GB',
        12,
        TRUE,
        NULL,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'seed-hdd-1tb',
        'hdd-1tb',
        'HDD 1TB',
        '1 TB hard disk drive for desktop computers, CCTV recorders, DVRs, NVRs, and dependable everyday storage.',
        11000,
        ARRAY['/uploads/bits-logo.png'],
        'HDD',
        'Mixed',
        '1 TB',
        24,
        TRUE,
        NULL,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'seed-hdd-2tb',
        'hdd-2tb',
        'HDD 2TB',
        '2 TB hard disk drive for higher-capacity desktop storage and continuous CCTV, DVR, or NVR recording.',
        19000,
        ARRAY['/uploads/bits-logo.png'],
        'HDD',
        'Mixed',
        '2 TB',
        24,
        TRUE,
        NULL,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'seed-hdd-3tb',
        'hdd-3tb',
        'HDD 3TB',
        '3 TB hard disk drive for high-capacity storage, CCTV surveillance systems, DVRs, and NVRs.',
        21000,
        ARRAY['/uploads/bits-logo.png'],
        'HDD',
        'Mixed',
        '3 TB',
        24,
        TRUE,
        NULL,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'seed-hdd-4tb',
        'hdd-4tb',
        'HDD 4TB',
        '4 TB hard disk drive for extended CCTV retention, DVR and NVR recording, and large desktop storage requirements.',
        35000,
        ARRAY['/uploads/bits-logo.png'],
        'HDD',
        'Mixed',
        '4 TB',
        24,
        TRUE,
        NULL,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'seed-hdd-10tb',
        'hdd-10tb',
        'HDD 10TB',
        '10 TB hard disk drive for large surveillance installations, long recording retention, and high-capacity storage.',
        81000,
        ARRAY['/uploads/bits-logo.png'],
        'HDD',
        'Mixed',
        '10 TB',
        12,
        TRUE,
        NULL,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    )
ON CONFLICT ("slug") DO NOTHING;
